### ISSUE TITLE
 Standard names: atmospheric radar terms

### ISSUE THREAD

**Issue by ingemarh** [cf-convention/vocabularies#21]
Proposer's name: Ingemar Häggström
Date 1 Oct 2021

Term: radial_velocity_of_scatterers_away_from_instrument
Description: A velocity is a vector quantity. "Radial velocity away from instrument" means the component of the velocity along the line of sight of the instrument where positive implies movement away from the instrument (i.e. outward). The "instrument" (examples are radar and lidar) is the device used to make the observation. The "scatterers" are what causes the transmitted signal to be returned to the instrument (examples are aerosols, hydrometeors and refractive index irregularities), of whatever kind the instrument detects. A standard name referring to radial velocity "toward_instrument" should be used for a data variable having the opposite sign convention.
Units: ms-1

Term: volume_backscatter_of_radiation_power_in_air_of_instrument
Description: The "instrument" (examples are radar and lidar) is the device used to make the observation. The "scatterers" are what causes the transmitted signal to be returned to the instrument (examples are aerosols, hydrometeors and refractive index irregularities), of whatever kind the instrument detects. A standard name referring to the recieved power of the signal at the instrument.
Units: W

Term: volume_backscatter_radiation_roundtrip_travel_time_in_air_of_instrument
Description: The "instrument" (examples are radar and lidar) is the device used to make the observation. The "scatterers" are what causes the transmitted signal to be returned to the instrument (examples are aerosols, hydrometeors and refractive index irregularities), of whatever kind the instrument detects. A standard name referring to time taken for a signal to propagate from the emitting instrument to a reflecting volume and back again to the instrument.
Units: s

Term: volume_backscatter_radiation_spectralwidth_in_air_of_instrument
Description: The "instrument" (examples are radar and lidar) is the device used to make the observation. The "scatterers" are what causes the transmitted signal to be returned to the instrument (examples are aerosols, hydrometeors and refractive index irregularities), of whatever kind the instrument detects. A standard name referring to frequency width of the received signal.
Units: Hz

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
