### ISSUE TITLE
 Standard names: Deprecate "convective_precipitation_rate" in favour of existing "lwe_convective_precipitation_rate"

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/vocabularies#210]
**Lars Bärring**

**2024-08-12**

The standard name `convective_precipitation_rate` with units `m s-1` is problematic because the term *precipitation* aggregates different phases of water meaning that the thickness is ill-defined (see [here (at the bottom)](https://github.com/cf-convention/vocabularies/issues/51#issue-2435459679) and [here](https://github.com/cf-convention/vocabularies/issues/51#issuecomment-2276233840)). Hence:

 Alias `convective_precipitation_rate` in favour of existing `lwe_convective_precipitation_rate`

**Comment by taylor13** [comment]
While we're at it, and pending outcome of the discussion at https://github.com/cf-convention/vocabularies/issues/67, perhaps the description of these needs to be revised to indicate this is *surface* precipitation.

**Comment by efisher008** [comment]
Hi Lars @larsbarring ,

The name `convective_precipitation_rate` has been aliased to the existing name `lwe_convective_precipitation_rate` as you recommended. This issue should remain open as there will be a need to revise the definition of the phrase "precipitation" in the description to be consistent with #67, as @taylor13 has mentioned. 

Best wishes,
Ellie

**Comment by larsbarring** [comment]
Thanks Ellie @efisher008!

@taylor13: I think that all standard names related to any form of precipitation and expressed as a rate having units `m s-1` have to refer to what is arriving at the ground because the unit **m**  I *think* is only relevant in relation to a surface (as opposed to a layer in the atmosphere). 

@efisher008: As this issue is specifically dealing with the aliasing (and nothing else) maybe we could close it? I am not sure it is helpful to spread out the revision of descriptions of all the many different "precip" standard names in several issues. What do you think?

**Comment by JonathanGregory** [comment]
I agree with Lars's comment

> @taylor13: I think that all standard names related to any form of precipitation and expressed as a rate having units `m s-1` have to refer to what is arriving at the ground because the unit **m**  I *think* is only relevant in relation to a surface (as opposed to a layer in the atmosphere). 

It refers to the rate at which the precipitation accumulates in a notional collector on the ground. It's the rate of change of the accumulated thickness. If it was in the atmosphere `m s-1` would probably refer to the speed of fall, which is a different thing.
