### ISSUE TITLE
 Standard names: Propose new additions to the standard names table (Soil Moisture at different depths)

### ISSUE THREAD

**Issue by YueLi92** [cf-convention/vocabularies#211]
**CMIP7 Land & Land Ice Data Request Author Team
Soil Moisture at different depths
Proposer's name: Yue Li
Date: Aug 20, 2024**

Based on the recent scientific need to consider soil moisture at different layers, I'd like to propose standard names for soil moisture at the depths of 5cm, 10cm, 20cm, 50cm, and 100cm. The naming of these physical parameters follows the existing "mrso", whose CF Standard Name is _mass_content_of_water_in_soil_. The number of corresponding depths has been added to the end of the term.

The addition is based on my role as the co-lead of the CMIP7 Land and Land Ice Data Request Team and my discussion with Dr. David Lawrence (NSF NCAR). Several supporting scientific references are selected here: (DOI 10.1088/1748-9326/ac6f6d, doi.org/10.1016/j.rse.2021.112706, doi:10.5194/gmd-17-1869-2024).

Please find the proposed new standard names of soil moisture at different layers below. Thank you!

**- Term** _Long Name_ Units

1. **mrso5** _mass_content_of_water_in_soil_5cm_ kg m-2
    Mean soil water content at a depth of 5 cm

2. **mrso10** _mass_content_of_water_in_soil_10cm_ kg m-2
    Mean soil water content at a depth of 10 cm

3. **mrso20** _mass_content_of_water_in_soil_20cm_ kg m-2
    Mean soil water content at a depth of 20 cm

4. **mrso50** _mass_content_of_water_in_soil_50cm_ kg m-2
    Mean soil water content at the depth of 50 cm

5. **mrso100** _mass_content_of_water_in_soil_100cm_ kg m-2
    Mean soil water content at the depth of 100 cm

**Comment by taylor13** [comment]
I think the existing standard_name ``lwe_thickness_of_moisture_content_of_soil_layer`` should be satisfactory for this purpose.  The generic units for this standard name are meters, not kg m-2, so an assumption would need to be made concerning the density of water.

**Comment by YueLi92** [comment]
Thanks. We will probably try to propose a variable based on this existing standard_name. But this multi-layer variable might be too big if the Data Request team wants a very high temporal frequency (e.g., 3hr) output. For example, a 3-hr output of soil moisture at only 5cm would be more feasible. If one variable containing all-layer soil moisture, the output might be too big regarding the size of the output. We need more discussion on this with the Land&Land Ice team.

**Comment by taylor13** [comment]
Hi @YueLi92.  The "moisture content of soil layer" standard name can be used for variable limited to a single layer. I just noticed that there is another variable that is closer to your earlier suggestion: ``mass_content_of_water_in_soil_layer`` with units of kg m-2.  Its description in the standard name glossary is:
```
  "Content" indicates a quantity per unit area. "Water" means water in all phases. "Layer" means any
 layer with upper and lower boundaries that have constant values in some vertical coordinate. There 
must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model
 layers, the vertical coordinate can be "model_level_number", but it is recommended to specify a 
physical coordinate (in a scalar or auxiliary coordinate variable) as well. Quantities defined for a soil 
layer must have a vertical coordinate variable with boundaries indicating the extent of the layer(s).
```
You need to define a vertical coordinate even in the case of a single variable and define its bounds.  You can do this in a couple of different ways, but defining a "scalar" coordinate as described [here]( http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#scalar-coordinate-variables) is a good one.  Please add a comment if further guidance is needed.

**Comment by efisher008** [comment]
Hi all @YueLi92 @japamment @taylor13,

As there has been no further discussion and the action (to use the existing standard name [above](https://github.com/cf-convention/vocabularies/issues/211#issuecomment-2429847901)) appears to be resolved, can this issue now be closed?

Best regards,
Ellie

**Comment by taylor13** [comment]
fine with me.

**Comment by YueLi92** [comment]
Thank you all for the help! Fine for me to close this as we decide to use the mrsol instead of proposing new variable name.

**Comment by japamment** [comment]
Thank you @YueLi92. I am closing this issue now because a new standard name is no longer required.
