### ISSUE TITLE
 Standard names: Propose new name for integrated surface snow mass for use in SIMIP and CMIP7

### ISSUE THREAD

**Issue by pderepen** [cf-convention/vocabularies#216]
On behalf of the Sea Ice Model Intercomparison Project (SIMIP) for CMIP7, I would like to propose a standard name for the integrated mass of snow over a certain region.

Name: surface_snow_mass
Units: kg
Description: Surface snow amount refers to the amount on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants. The horizontal domain over which surface snow mass is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions.

Thanks for considering this proposal.

Proposer's name: Patricia DeRepentigny
Date: 30 August 2024

**Comment by JonathanGregory** [comment]
Dear Patricia @pderepen 

Thanks for your proposal. `surface_snow_mass` would be the area-integral of `surface_snow_amount` - is that right? It sounds fine to me. It's analogous to `land_ice_mass` and `sea_ice_mass`, for instance.

Best wishes

Jonathan

**Comment by pderepen** [comment]
Dear Jonathan @JonathanGregory

That is exactly right! We would like something analogous to `land_ice_mass` and `sea_ice_mass` but for surface snow to be able to evaluate the total mass of the cryosphere.

Best,
Patricia

**Comment by JonathanGregory** [comment]
Yes, that makes sense! Thanks. Jonathan

**Comment by taylor13** [comment]
Not relevant to the standard name discussion, but for the CMIP7 list of requested output, I think it would be much better to obtain the ``surface_snow_amount``, since the geographical distribution of snow mass will be needed for many studies.  It is not difficult to compute the total mass of snow over a region by then integrating ``surface_snow_amount``.  This shifts the burden from the modeling groups to the user, which I think is appropriate in this case.

**Comment by pderepen** [comment]
@taylor13 Thank you for the comment. In the CMIP7 (and CMIP6) list of requested output, we already have the variable `sisnmass` which represent the total mass of snow on sea ice divided by sea-ice area. With this, one would be able to compute the total mass of snow over a region. Interestingly, this variable is associated to the CF standard name `liquid_water_content_of_surface_snow` and not `surface_snow_amount`. I must admit that it's not clear to me which of the two is better suited to `sisnmass`, but if you have a strong opinion about it I would suggest you submit a comment about this here: https://bit.ly/CMIP-MIP-variable-comment

Regarding only having the gridded snow mass and not the hemisphere-integrated value to alleviate the burden on the modeling centers, we (as co-chairs of SIMIP) believe that these integrated values are actually very helpful to the users (the integrated sea ice variables were the most downloaded in CMIP6 by a large margin) and also prevent some user errors when integrating (e.g., multiplying by grid area instead of sea-ice area). And since this is a relatively small and simple term to compute for the modeling centers, we think it won't increase their burden significantly.

Hope this helps!

**Comment by JonathanGregory** [comment]
`liquid_water_content_of_surface_snow` refers to the liquid water which is contained within the snowpack. That's not the same thing as `lwe_thickness_of_surface_snow_amount`, which converts `surface_snow_amount` (`kg m-2`) into thickness (`m`) using the density of liquid water. I suspect that `sisnmass` has the wrong standard name.

**Comment by taylor13** [comment]
Jonathan is right.  I reviewed all the CMIP6 variables and this was one of quite a few that was almost certainly named incorrectly.  I will post more on the data request site given above.

**Comment by pderepen** [comment]
@JonathanGregory @taylor13 Thanks to you both, I believe you are correct that the CF standard name for `sisnmass` should be `surface_snow_amount` and not `liquid_water_content_of_surface_snow`. I will submit a comment to rectify this in the CMIP7 data request.

**Comment by pderepen** [comment]
Are there any outstanding concerns regarding the proposal of `surface_snow_mass` as a new CF standard name? If not, can we move forward with the proposal?

Patricia

**Comment by taylor13** [comment]
Hi Patricia,
I don't object to the standard name, but I would like to see what discussions of my concerns have taken place on the CMIP data request website. (I think I submitted a comment there, but I don't know how to see the follow-on.)  Can you point me to that discussion?  Thanks.

**Comment by pderepen** [comment]
Hi Taylor,
I'm not sure I understand what concern you are referring to. Also, I could not find the comment you submitted. Do you remember what you commented on specifically (i.e. which physical parameter or variable)?
Thanks, Patricia

**Comment by taylor13** [comment]
I think I followed your link to the form and commented on the variable you are requesting, but I can't find any links to it in the airtable.

**Comment by efisher008** [comment]
Hi Patricia @pderepen,

Thank you for your proposal and the discussion on this name. The name was entered into the editor by Alison @japamment on 24th September and the term description can be viewed here: https://cfeditor.ceda.ac.uk/proposal/5465

I believe this issue has come to a consensus, and so the name `surface_snow_mass` can be accepted after 7 days if there are no further comments to the contrary. It sounds as though there are also some actions to be taken with the CMIP7 data request (by Patricia and Karl), so an update on these would also be welcome. 

Best regards,
Ellie Fisher

**Comment by pderepen** [comment]
Hi Ellie @efisher008,

Great, thanks for moving this forward!

@taylor13 I also cannot find any related comment in the airtable. If you still have concerns regarding this, feel free to use to same form to submit another comment so that it can be reviewed by the thematic author team.

Best,
Patricia

**Comment by japamment** [comment]
Dear Patricia @pderepen,

Your proposed name is now accepted for publication and will be added in the next update of the standard name table, planned for 16th/17th December.

`surface_snow_mass`
**Units:** kg
**Description:** Surface snow amount refers to the amount on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants. The horizontal domain over which surface snow mass is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions.

Best wishes,
Alison

**Comment by pderepen** [comment]
Awesome, thank you @japamment !

Best wishes,
Patricia

**Comment by japamment** [comment]
The name discussed in this issue is now in the published standard name table, so closing this issue as complete.
