### ISSUE TITLE
 Standard names: Propose new names for fisheries board parameters for use in Impacts & Adaptation team

### ISSUE THREAD

**Issue by ioloi1128** [cf-convention/vocabularies#224]
As discussed within the fisheries board in Impact and Adaptation team, I would like to propose two new standard names.

Name: turb
Title:  Turbidity of Coastal Runoff and seawater 
CF Standard Name: turbidity_of_seawater
Units: nephelometric turbidity units (NTU)
Description: turbidity of seawater

Name:  ppalg
Title:  Algal Production
CF Standard Name: tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_algal_production
Units: mol m-3 s-1
Description: Algal Production

Thanks for considering this proposal.

Proposer's name: Wan-Ling Tseng
Date: 14 September 2024

**- Term** Proposed term to appear in the vocabulary

**- Description** A brief description to explain the meaning of the term

**- Units** (If applicable).

**Comment by JonathanGregory** [comment]
Dear @ioloi1128

Thanks for your proposals.

The first quantity you request is already in the standard name table as `sea_water_turbidity`.

For the second one, I wonder what you mean by "production". Is it gross or net primary production? If net, I think this should be `tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_net_primary_production_by_algae`. Would that be correct?

Best wishes

Jonathan

**Comment by ioloi1128** [comment]
Dear Jonathan,

Thank your for the conformation.

1. The turbidity can be removed from my proposal.
2. Yes, it is production. "net" is also better for our application. Thank
you for the correction again.

Best regards
Wan-Ling

JonathanGregory ***@***.***> 於 2024年9月17日 週二 上午4:34寫道：

**Comment by efisher008** [comment]
Dear @ioloi1128,

Thank you for your proposal. The name `tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_net_primary_production_by_algae` has been added to the CF editor. The following phrases were suggested to add to the description - would you agree with these being used to describe your proposed name?

_The phrase "tendency_of_X" means derivative of X with respect to time. Particulate means suspended solids of all sizes. Net primary production is the excess of gross primary production (the rate of synthesis of biomass from inorganic precursors) by autotrophs ("producers"), for example, photosynthesis in plants or phytoplankton, over the rate at which the autotrophs themselves respire some of this biomass. In the oceans, carbon production per unit volume is often found at a number of depths at a given horizontal location. That quantity can then be integrated to calculate production per unit area at the location. Standard names for production per unit area use the term "productivity". "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. The phrase "expressed_as" is used in the construction "A_expressed_as_B", where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Mole concentration" means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen"._

Best regards,
Ellie Fisher

**Comment by ioloi1128** [comment]
Yes, thank you.

**Comment by efisher008** [comment]
Hi @ioloi1128,

The phrases mentioned [here](https://github.com/cf-convention/vocabularies/issues/224#issuecomment-2423150446) have been added to the description of the name `tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_net_primary_production_by_algae`. The entry in teh Chttps://cfeditor.ceda.ac.uk/proposal/5470

Would you like to add anything else to the description of your proposed name? Given the phrases cover the meaning fairly well, I would perhaps suggest removing the original text "algal production" as I am not sure what it adds to the meaning. Please let me know if you would like to revise this. 

Best,
Ellie

**Comment by efisher008** [comment]
Hi @ioloi1128,

As there has been no further comment on this issue, I have removed the text "algal production" from the start of the name and started the 7 day period to acceptance. If there are no further questions or changes during this time, the proposed name will be accepted and published in the next version of the standard name table (scheduled for mid-November). 

Best wishes,
Ellie
