### ISSUE TITLE
 Standard names: propose new names for Marine Ecosystems board in Impact and Adaptation team

### ISSUE THREAD

**Issue by damariszurell** [cf-convention/vocabularies#225]
As discussed within the Marine Ecosystems board in Impact and Adaptation team, I would like to propose two new standard names.

Name: intppcocco
Title: Net primary organic carbon production by coccolithophores
CF Standard Name: net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_coccolithophores
Units: mol m-2 s-1
Description: Vertically integrated primary (organic carbon) production by the coccolithophores component alone

Name: intppnano
Title: Net primary organic carbon production by nanophytoplankton
CF Standard Name: net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_nanophytoplankton
Units: mol m-2 s-1
Description: Vertically integrated primary (organic carbon) production by the nanophytoplankton component alone

Thanks for considering this proposal.

Proposer's name: Damaris Zurell
Date: 15 September 2024

**Comment by JonathanGregory** [comment]
Dear @damariszurell

Thanks for your proposals, which look fine to me, being similar to existing standard names. Are coccolithophores a subset of calcareous phytoplankton?

Best wishes

Jonathan

**Comment by damariszurell** [comment]
Dear @JonathanGregory
Yes, that's correct, coccolithophores are a subset of calcareous phytoplankton.
Best,
Damaris

**Comment by efisher008** [comment]
Dear Damaris @damariszurell,

Thank you for your proposal. The proposed names have been added to the CF editor and can be viewed here:

`net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_coccolithophores` - https://cfeditor.ceda.ac.uk/proposal/5471
`net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_nanophytoplankton` - https://cfeditor.ceda.ac.uk/proposal/5472

I think the descriptions can be expanded. There are suggestions from the CF phrasebank - could these possibly be added?
_Phytoplankton are algae that grow where there is sufficient light to support photosynthesis. Net primary production is the excess of gross primary production (rate of synthesis of biomass from inorganic precursors) by autotrophs ("producers"), for example, photosynthesis in plants or phytoplankton, over the rate at which the autotrophs themselves respire some of this biomass. "Productivity" means production per unit area. "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. The phrase "expressed_as" is used in the construction "A_expressed_as_B", where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A._

Best regards,
Ellie

**Comment by efisher008** [comment]
Dear Damaris @damariszurell,

I have added the new description text to both names. It looks like this proposal has now reached consensus, so we can start the 7 day period to acceptance. If there are no further comments/issues raised in the next week, the names will be accepted and published in the Standard Names table (this will now have to wait until after v87 is released, as this is planned for the start of next week). Thanks again for the proposal and support with the discussion.

Best regards,
Ellie

**Comment by efisher008** [comment]
Dear Damaris,

The 7 day period has now passed without further comments or suggestions, and these names have now been accepted in the CF editor. They will be published in the next release of the Standard Name table, v88, which is currently scheduled for December this year. Thank you again for your proposal. 

Best regards,
Ellie

**Comment by japamment** [comment]
The names discussed in this issue are now in the published standard name table, so closing this issue as complete.
