### ISSUE TITLE
 Standard names: volume fraction of pelite in sea floor sediment

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/vocabularies#229]
Hi, just a single standard_name to propose in this thread.

## volume_fraction_of_pelite_in_sea_floor_sediment
**Definition:** "Volume fraction" is used in the construction volume_fraction_of_X_in_Y, where X is a material constituent of Y. It is evaluated as the volume of X divided by the volume of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. "Sea floor sediment" is sediment deposited at the sea bed. "Pelite" is sediment less than 0.063 millimeters in diameter.

**Canonical units**: 1

**Comment by efisher008** [comment]
Hi Luke,

Thank you for your proposal. I have added this name to the CF editor. There is no name currently containing `pelite` in the table, but this follows the general formatting of `volume_fraction_of_oxygen_in_sea_floor_sediment_pore_water`. I will add `pelite` to the phrase list for use in future standard name descriptions.

The entry in the CF editor can be viewed here: https://cfeditor.ceda.ac.uk/proposal/5486

Just to check my understanding: there's no additional compositional requirement for pelite that should be added to the description, just the size classification? Is it the case that only clays are sufficiently fine-grained to occupy that part of the Udden-Wentworth scale?

Best wishes,
Ellie

**Comment by lhmarsden** [comment]
Hi Ellie,

Thanks for this reply.

I have spoken to my geologist colleague about this. He says "There is no additional compositional requirement for pelite that should be added to the description, it is just a size classification. And yes, mainly clayey fine-grained sediment rock can go through the scale."

Kind regards
Luke

**Comment by efisher008** [comment]
Hi Luke, 

Thank you for checking this. I have added `pelite` to the CF phrase list and will start the 7 day period for acceptance of your proposed name. If there are no further comments for discussion, this will then be published in the next Standard Names table release which is scheduled for mid November. 

Best wishes,
Ellie

**Comment by lhmarsden** [comment]
Thanks, @efisher008 !

**Comment by japamment** [comment]
The name proposed here has been published in V87 of the standard name table, so closing this issue now.
