### ISSUE TITLE
 Standard names: area fraction

### ISSUE THREAD

**Issue by taylor13** [cf-convention/vocabularies#24]
In the descriptions of standard names that include the string "area_fraction", the guidance provided includes the following:
```
"Area fraction" is the fraction of a grid cell's horizontal area that has some 
characteristic of interest.  It is evaluated as the area of interest divided by the 
grid cell area.
```
This seems to rule out defining such fractions as the area of interest divided by the area of some _portion_ of the grid cell (e.g., the area of snow on sea ice divided by the area of sea ice, which in general differs from the area of snow in a grid cell divided by the area of the grid cell).   

This is a problem that has cropped up in CMIP where, for example, the fraction of sea ice area covered by melt ponds was incorrectly assigned the standard name area_fraction.  According to the guidance for area_fraction, the variable should be interpreted as fraction of _grid cell_ area covered by melt ponds, not fraction of _sea ice_ area covered by melt ponds.

In order to accommodate fractions of some _portion_ of a grid cell (rather than the entire grid cell), we might adopt one of the following:

1. define a new standard name, ``partial_area_fraction``.  (This idea was suggested to me by @martinjuckes.)  
2. revise the restrictive guidance to read:
```
"Area fraction" is the fraction of a grid cell's horizontal area that has some 
characteristic of interest.  It is evaluated as the area of interest divided by the 
grid cell area, or if the cell_methods restricts the evaluation to some portion of 
that grid cell (e.g. "where sea_ice"), then it is the area of interest divided by the 
area of the identified portion.
``` 
I initially favored Martin's suggestion, but now realize that there are a number of other standard names that include the string "area_fraction" (``surface_snow_area_fraction``, ``tendency_of_sea_ice_area_fraction_due_to_thermodynamics``, and many more), which also might need a second standard name with "area_fraction" replaced by "partial_area_fraction".  Another virtue of the second option is that the mistake in using area_fraction in CMIP would be corrected by relaxing the restriction that the fraction's divisor should be the full grid cell area.

**Comment by japamment** [comment]
Dear Karl @taylor13 and Jonathan @JonathanGregory,

Apologies for having overlooked this issue, and that my response is long overdue.

I have a few questions about the proposal.

I can see the benefit of extending the description of area_fraction to allow for fractions of portions of grid cells (identified by cell_methods using phrases such as "where sea_ice") and how this might apply to the melt pond example in CMIP6 data. For this usage, would the method part of cell_methods be "mean"? This would seem to make sense for describing the total area within a grid cell having a given characteristic divided by the total area of the identified portion. What cell_method was used in the CMIP6 data?

If "mean" is always the correct cell_method to use for an area_fraction then I think we should include a statement to that effect in the standard name description.

Also, is the intention that the proposed change should be applied to all X_area_fraction standard names? It seems to me that it should.

Best wishes,
Alison

**Comment by taylor13** [comment]
In common usage of area_fraction, I think "mean" is often the appropriate method for the spatial dimension, but not necessarily the time dimension, and in general I can imagine that sometimes "standard_deviation" or some other cell method would be called for.  

I agree that the description should apply to all X_area_fraction standard names.

**Comment by efisher008** [comment]
Hi @japamment @taylor13,

Were there any agreed actions from this discussion?

Best wishes,
Ellie

**Comment by taylor13** [comment]
I think we should replace some (or all?) of the current descriptions of standard_names that include the text "area_fraction" with what I have written in https://github.com/cf-convention/vocabularies/issues/24#issuecomment-2255936782.   I don't think there have been objections to that.  I can help with whether it is "some" or "all" if we are in general agreement.

**Comment by JonathanGregory** [comment]
I agree with applying Karl's words.

**Comment by efisher008** [comment]
Hi Karl @taylor13,

I agree this seems sensible. If you could help with identifying which names to apply this to, that would be much appreciated.
From the current version (v85) of the Standard Names table, I found the following names containing `area_fraction`:

- `area_fraction`
- `area_fraction_below_surface`
- `area_fraction_of_day_defined_by_solar_zenith_angle`
- `area_fraction_of_night_defined_by_solar_zenith_angle`
- `area_fraction_of_twilight_defined_by_solar_zenith_angle`
- `burned_area_fraction`
- `clear_sky_area_fraction`
- `cloud_area_fraction`
- `cloud_area_fraction_in_atmosphere_layer`
- `convective_cloud_area_fraction`
- `convective_cloud_area_fraction_in_atmosphere_layer`
- `floating_ice_shelf_area_fraction`
- `fog_area_fraction`
- `fraction_of_time_with_sea_ice_area_fraction_above_threshold`
- `gross_rate_of_decrease_in_area_fraction`
- `gross_rate_of_increase_in_area_fraction`
- `grounded_ice_sheet_area_fraction`
- `high_type_cloud_area_fraction`
- `ice_cloud_area_fraction`
- `ice_cloud_area_fraction_in_atmosphere_layer`
- `isccp_cloud_area_fraction`
- `land_area_fraction`
- `land_ice_area_fraction`
- `liquid_water_cloud_area_fraction`
- `liquid_water_cloud_area_fraction_in_atmosphere_layer`
- `low_type_cloud_area_fraction`
- `medium_type_cloud_area_fraction`
- `permafrost_area_fraction`
- `sea_area_fraction`
- `sea_ice_area_fraction`
- `snow_area_fraction_viewable_from_above`
- `stratiform_cloud_area_fraction`
- `stratiform_cloud_area_fraction_in_atmosphere_layer`
- `surface_snow_area_fraction`
- `tendency_of_sea_ice_area_fraction_due_to_dynamics`
- `tendency_of_sea_ice_area_fraction_due_to_ridging`
- `tendency_of_sea_ice_area_fraction_due_to_thermodynamics`
- `vegetation_area_fraction`

There are also three accepted (but not yet published) names in the CF editor with this term:

- `modis_ice_topped_cloud_area_fraction` ([#52](https://github.com/cf-convention/vocabularies/issues/52)) 
- `modis_liquid_topped_cloud_area_fraction` ([#52](https://github.com/cf-convention/vocabularies/issues/52)) 
- `modis_cloud_area_fraction` ([#52](https://github.com/cf-convention/vocabularies/issues/52)) 

Best wishes,
Ellie

**Comment by taylor13** [comment]
Thanks for the list.  I think the following text should be included in the description of *all* the above standard names.
```
"Area fraction" is the fraction of a grid cell's horizontal area that has some 
characteristic of interest.  It is evaluated as the area of interest divided by the 
grid cell area, or if the cell_methods restricts the evaluation to some portion of 
that grid cell (e.g. "where sea_ice"), then it is the area of interest divided by the 
area of the identified portion.
```
best,
Karl

**Comment by efisher008** [comment]
Hi @taylor13,

Thank you for your reply and for re-posting the text. This has replaced the original definition of `area_fraction` in all above names and has been added to the accepted names relating to MODIS variables. 

The rest of the definition was unchanged and so the full text reads as follows:
 _"Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area, or if the cell_methods restricts the evaluation to some portion of that grid cell (e.g. "where sea_ice"), then it is the area of interest divided by the area of the identified portion. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. To specify which area is quantified by a variable with standard name area_fraction, provide a coordinate variable or scalar coordinate variable with standard name area_type. Alternatively, if one is defined, use a more specific standard name of X_area_fraction for the fraction of horizontal area occupied by X._

I have also amended the definition of the phrase `area_fraction` in the CF phrasebank to the above text.

Are there any other actions from this issue that need to be highlighted? 

Best,
Ellie

**Comment by taylor13** [comment]
Thanks Ellie.  The above looks fine.  To be sure, I assume the full description above would only be used for the stand-alone ``area_fraction``, not all the other "area fraction" standard names (since the last 2 sentences in the description would not generally apply).  Right?

**Comment by efisher008** [comment]
Hi @taylor13,

That is correct - the full description is only applied to `area_fraction`.

Best,
Ellie
