### ISSUE TITLE
 Standard names: *Ocean surface elevation without the contributions of ocean tides nor atmospheric pressure forcing (invert barometer)*

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/vocabularies#37]
Hello,

I am Aurore BIARDEAU from Mercator Ocean international, working for Copernicus Marine service.
Date : 07-03-2024

We are in the process of implementing a new variable in the Copernicus Marine service, and we would be happy to have your feedback on our proposal : 

- standard_name : `non_tidal_non_ib_elevation_of_sea_surface_height`
- unit : m
- definition : "Sea surface height" is a time-varying quantity. The phrase "non_tidal_non_ib_elevation" describes the contribution to sea surface height variability made by processes other than astronomic forcing of the ocean and shallow water resonance of tidal components, or variations in air pressure.

The definition is inspired by standard_name `non_tidal_elevation_of_sea_surface_height` whose definition corresponds to sea_surface_height + invert_barometer.

I can provide more information from my expert colleagues if needed,

Kind regards,
Aurore

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
