### ISSUE TITLE
 Standard names: *Invert Barometer : Ocean surface elevation due to atmospheric pressure*

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/vocabularies#38]
Hello,

I am Aurore BIARDEAU from Mercator Ocean international, working for Copernicus Marine service.
Date : 07-03-2024

We are in the process of implementing a new variable in the Copernicus Marine service, and we would be happy to have your feedback on our proposal :

standard_name : `sea_surface_height_amplitude_due_to_invert_barometer`
unit : m
definition : The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Invert barometer" means variations in air pressure that give rise to corresponding variations in sea surface topography.

The definition is inspired by the definition of the standard_name `sea_surface_height_correction_due_to_air_pressure_at_low_frequency`, which corresponds to the IB correction in level 2 altimetry data.

I can provide more information from my expert colleagues if needed,

Kind regards,
Aurore

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
