### ISSUE TITLE
 Standard names: *Ocean surface elevation due to load tides*

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/vocabularies#41]
Hello,

I am Aurore BIARDEAU from Mercator Ocean international, working for Copernicus Marine service.
Date : 07-03-2024

We are in the process of implementing a new variable in the Copernicus Marine service : **Load tide elevation**, which is the Ocean surface elevation due to load tides (deformation of the Earth due to the weight of the water masses displaced by ocean tides). 

We would be happy to have your feedback on our proposal :

standard_name : `sea_surface_height_amplitude_due_to_load_tide`
unit : m
definition : The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Tides are a significant contributor to the observed sea surface height. The load tidal component of sea surface height describes the variability of the sea surface due to the deformation of the Earth because of the weight of the water masses displaced by ocean tides.

I can provide more information from my expert colleagues if needed,

Kind regards,
Aurore

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
