### ISSUE TITLE
 Standard names: additional active acoustic standard names

### ISSUE THREAD

**Issue by jcermauwedu** [cf-convention/vocabularies#44]
**Proposer's name**: John Horne (jhorne@uw.edu), Mark Yamane (mtyamane@uw.edu) and Rob Cermak (jcerma@uw.edu)

**Date**: 18 March 2024

**Notes**: We would like to propose additional standard names so that proposed active acoustic information may be added to the IOOS Glider DAC and meets compliance requirements through use of the IOOS Compliance Checker.  The related publication for this proposal may be found here, https://academic.oup.com/icesjms/article/69/2/184/701699, with the primary reference Urmy et. al (2012) doi:10.1093/icesjms/fsr205.   Some of these have already been defined in a prior accepted proposal (#153).  Community software impacts include the IOOS Compliance Checker (https://github.com/ioos/compliance-checker), echopype (https://github.com/OSOceanAcoustics/echopype), pyglider (https://github.com/c-proof/pyglider) and GUTILS (https://github.com/SECOORA/GUTILS).  Issues will be raised and linked to this issue so they will have an opportunity to make comments and suggestions.  Notice will also be placed in appropriate Slack channels on UG2 and IOOS to raise additional awareness.

**Proposed Names**

**acoustic_proportion_occupied_in_sea_water**
**Description**: Acoustic proportion occupied is occupied volume divided by the volume sampled. Occupied volume is the integral of the ratio of acoustic_volume_backscattering_strength_in_sea_water above -90 dB to the reference value, 1 m2 m-2. For further details see Urmy et. al (2012) doi:10.1093/icesjms/fsr205.
**Units**: 1

**acoustic_index_of_aggregation_in_sea_water**
**Description**: Acoustic index of aggregation is the depth integral of squared volume backscattering coefficient divided by the squared area backscattering coefficient. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. Area backscattering coefficient is the integral of the volume backscattering coefficient over a defined distance. The parameter is computed to provide a value that represents the patchiness of biomass in the water column in the field of fisheries acoustics - the value is high when small areas are much denser than the rest of the distribution. The parameter is also the reciprocal of acoustic_equivalent_area_in_sea_water. For further details see Urmy et. al (2012) doi:10.1093/icesjms/fsr205 and Woillez et. al (2007) doi.org/10.1093/icesjms/fsm025.
**Units**: m-1

**acoustic_centre_of_mass_in_sea_water**
**Description**: Acoustic centre of mass is the average of all sampled depths weighted by their volume backscattering coefficient. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. For further details see Urmy et. al (2012) doi:10.1093/icesjms/fsr205.
**Units**: m

**acoustic_inertia_in_sea_water**
**Description**: Acoustic inertia is the sum of squared distances from the acoustic_centre_of_mass weighted by the volume backscattering coefficient at each distance and normalized by the total area backscattering coefficient. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. Area backscattering coefficient is the integral of the volume backscattering coefficient over a defined distance. For further details see Urmy et. al (2012) doi:10.1093/icesjms/fsr205 and Bez and Rivoirard (2001) doi:10.1016/S0165-7836(00)00241-1.
**Units**: m-2

**acoustic_equivalent_area_in_sea_water**
**Description**: Acoustic equivalent area is the squared area backscattering coefficient divided by the depth integral of squared volume backscattering coefficient. Area backscattering coefficient is the integral of the volume backscattering coefficient over a defined distance. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. The parameter is computed to provide a value that represents the area that would be occupied if all data cells contained the mean density and is the reciprocal of acoustic_index_of_aggregation_in_sea_water. For further details see Urmy et. al (2012) doi:10.1093/icesjms/fsr205 and Woillez et. al (2007) doi.org/10.1093/icesjms/fsm025.
**Units**: m

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
