### ISSUE TITLE
 Standard names: additional wildland fire indexes

### ISSUE THREAD

**Issue by akessenich** [cf-convention/vocabularies#46]
This is an addendum to names proposed in issue cf-convention/vocabularies#142. 
This work is related to the NA-CORDEX archive and supported by NSF Growing Convergence Research.

**Proposer's name:** Lee Kessenich, National Center for Atmospheric Research

**Date:** April 18, 2024

**- Term:** nfdrs_1_hour_fuel_moisture_content
**- Description:** 1 hour fuel moisture (FM1) represents the modeled moisture content of dead fuels consisting of herbaceous plants or roundwood less than one-quarter inch in diameter. It also includes the uppermost layer of litter on the forest floor. The 1-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), daily downwelling shortwave radiation, daily maximum temperature and minimum relative humidity, and daily precipitation values. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage. It was designed for use in the continental United States, and all its components are relative, not absolute. *adapted from Gaining a Basic Understanding of NFDRS
**- Units:** % 

**- Term:** nfdrs_10_hour_fuel_moisture_content
**- Description:** 10 hour fuel moisture (FM10) represents the modeled moisture content of dead fuels consisting of roundwood in the size range of one quarter to 1 inch in diameter and very roughly, the layer of litter extending from just below the surface to three-quarters of inch below the surface. The 10-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), daily downwelling shortwave radiation, daily maximum temperature and minimum relative humidity, and daily precipitation values. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage. It was designed for use in the continental United States, and all its components are relative, not absolute. *adapted from Gaining a Basic Understanding of NFDRS
**- Units:** % 

**- Term:** hot_dry_windy_index
**- Description:** The Hot-Dry-Windy Index is the product of windspeed and vapor pressure deficit. It is a fire weather index that indicates the influence that the atmosphere has on a fire through wind, heat, and moisture. Its units are largely meant to be ignored.
**- Units:** hPa m s-1

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
