### ISSUE TITLE
Standard name: *New variable - solid-Earth model VILMA*

### ISSUE THREAD

**Issue by SwatiGehlot** [cf-convention/vocabularies#47]
The below proposed is a new standard name variable (relative sea level change) as a part of solid earth model VILMA, developed within the German paleo-climate initiative, Project PalMod ([www.palmod.de](http://www.palmod.de/))

**Proposer's name**: Swati Gehlot, DKRZ, Hamburg
(technical description via Clemens Schannwell - [clemens.schannwell@mpimet.mpg.de](mailto:clemens.schannwell@mpimet.mpg.de))

**Date** 2024-05-07

**1. Relative sea-level change**

**Term**: relative_sea_level_change
**Description**: The change in local mean sea level relative to the local solid surface, i.e. sea floor
**Units**: m
**CMOR name**: rslc

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
