### ISSUE TITLE
 Standard names: 'land water' equivalents

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/vocabularies#48]
Hi,

This is not a typical request for a new CF standard name to be added. My understanding is that new standard names are added 'reactively' rather than 'proactively' based on what is requested. This is more of a 'proactive' request.

There are a lot of *...sea_water...* CF standard names. I am aware of some scientists who take measurements of lake or river water. I suspect these communities are not yet so engaged in the CF community since I can't find equivalent standard names for 'land' water.

Do you think the CF community should be proactive in adding equivalents for terrestrial science? I suspect the wording of the names and descriptions should be very similar - probably in most cases swapping 'sea_water' to 'land_water'. I have selected 'land_water' as it is consistent with 'land_ice' used in other standard names, and I see one standard name *land_water_amount*.

In my experience it takes a quite enthusiastic scientist to propose a new standard_name, particularly if they are new to NetCDF files. Maybe this more pro-active approach could be helpful if feasible in this case?

Luke

**Comment by efisher008** [comment]
This issue relates to "proactive" standard name proposals for future use cases in terrestrial science, which forms part of active discussions in other current issues in the GitHub vocabularies repository (e.g. #25, #65 as mentioned by Lars). This will feed into conversations at the upcoming CF workshop 2024 in Norrköping, Sweden, and therefore for now the issue has been considered concluded. If there is a need to reopen the issue following the workshop, this will be done.
