### ISSUE TITLE
 Standard names: *Global average sea level change due to water mass budget*

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/vocabularies#49]
Hello,
I am Aurore BIARDEAU from Mercator Ocean international, working for Copernicus Marine service.
Date : 13-05-2024

We are in the process of implementing a new variable in the Copernicus Marine service and we would be happy to have your feedback on our proposal :

standard_name : `global_average_sea_level_change_due_to_water_mass_budget `
definition : Global average mass volume sea level change is caused by water mass balance (evaporation – precipitation + runoff). This in turn results in a change in volume of the world ocean. Zero sea level change is an arbitrary level. Because global average sea level change quantifies the change in volume of the world ocean, it is not calculated necessarily by considering local changes in mean sea level

I can provide more information from my expert colleagues if needed,
Kind regards,
Aurore

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
