### ISSUE TITLE
 Add missing surface radiative flux diagnostic following on from #299

### ISSUE THREAD

**Issue by fmoconnor** [cf-convention/vocabularies#58]
This issue follows on from issue cf-convention/vocabularies#158, in which a range of standard names were proposed for inclusion in the CF convention for diagnostics from a diagnostic call to a model's radiation scheme, using a reference ozone field. 

The original proposer, Fiona O'Connor, has since realised that one name was missing from the original request and would like to propose it here for completeness. The corresponding 3d radiative flux diagnostic was included, and this new proposal refers to just the surface level from that 3d flux. 

The proposed new addition has the following name: 
Surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air

Units: W/m2

The surface called "surface" means the lower boundary of the atmosphere. The term "longwave" means longwave radiation. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds. The 3D ozone field acts as a reference ozone field in a diagnostic call to the model's radiation scheme. It is expressed in terms of mole fraction of ozone in air. It may be observation-based or model-derived. It may be from any time period. By using the same ozone reference in the diagnostic radiation call in two model simulations and calculating differences between the radiative flux diagnostics from the prognostic call to the radiation scheme and the diagnostic call to the radiation scheme with the ozone reference, an instantaneous radiative forcing for ozone can be calculated.

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).

**Comment by taylor13** [comment]
Sorry to reopen this, but I think some clarification is needed.

I'm pretty sure the surface emitted longwave radiation is independent of the anything except the surface properties (primarily emissivity and temperature).  As such, why does it need a standard name that mentions atmospheric conditions?  If one were to measure it, how does ``surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air``  differ from  ``surface_upwelling_longwave_flux_in_air``

Most standard names that include "surface" are interpreted as meaning "at the surface".  Are the surface longwave variables interpreted differently.  

(We may also need to reevaluate what "clouds" have to do with the surface upwelling flux of longwave.

**Comment by japamment** [comment]
Hi Fiona @fmoconnor 

Please could you respond to the question from @taylor13 in his post of October 14th. Although the name proposed in this issue has already been published in V86 of the standard name table, it may be necessary to revisit it and modify if needed.

Best wishes,
Alison

**Comment by fmoconnor** [comment]
Thanks for the comment @taylor13 and for the prompt @japamment.

Earlier this morning, I commented that I had perhaps made an error. However, in the context of radiative flux diagnostics for the data request for CMIP7 fast track, we've had a point made about surface upwelling, which has since prompted me to delete my previous comment. The point being made is the following:

> I am not a specialist in this field, but my understanding is in the past it was effectively assumed that the surface has an emissivity of 1.0 so people could use the all-sky upwelling flux. However, this is not the case for modern climate models which use emissivities < 1.0 which results in local differences of several W/m^2. This affects the ability to compute clear-sky surface budgets and cloud radiative effect.

So, it looks like it is correct to have the CF names `surface_upwelling_longwave_flux_in_air` and `surface_upwelling_longwave_flux_in_air_assuming_clear_sky` because they can be different. However, I note that there is no equivalent CF name for an "aerosol-free" CF name. So, the original request [(#158)](https://github.com/cf-convention/vocabularies/issues/158) was correct and this newer proposal of adding in a surface flux diagnostic `(surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air)` is incorrect and should be removed.

Sorry about the error on my part, 
Fiona

**Comment by taylor13** [comment]
Thanks for all the work you've done on this.

Begging your patience (and hoping you'll excuse my confusion), I still don't understand why ``surface_upwelling_longwave_flux_in_air`` and ``surface_upwelling_longwave_flux_in_air_assuming_clear_sky`` might differ.  (Similarly for presence or absence of ozone and/or aerosols.)  I am aware that surface LW emission depends on surface emissivity (as well as surface temperature), but is it really true that surface emissivity depends on the anything but surface properties?  

As I understand "assuming_clear_sky", when this calculation is made in a model, the only change made is in clearing the column of clouds, but not changing anything else (including not changing the surface temperature or anything else as the surface).  What am I not aware of here?

**Comment by fmoconnor** [comment]
@taylor13 I can't answer your question, I'm afraid. I'll ask those involved in RFMIP, who've recently decided to add `surface_upwelling_longwave_flux_in_air_assuming_clear_sky` (with physical parameter rluscs) to their CMIP7 data request alongside the all sky flux `surface_upwelling_longwave_flux_in_air` (with physical parameter rlus).

**Comment by fmoconnor** [comment]
@taylor13 Thanks again for re-opening this issue. It has led to a very constructive discussion with those involved in RFMIP and those involved in reviewing the RFMIP opportunity for the data request for CMIP7 Fast Track. 

The conclusions from that discussion are as follows:
1. LW emission from the surface is based on temperature and thus the same for all-sky vs clear-sky since the clear-sky calculation is not actually interactively changing Ts.  But with an emissivity less than 1, some of the downwelling LW from the lower atmosphere to the surface would not be perfectly absorbed and instead will be reflected. This reflection is then included as part of the LW upwelling diagnosis and the amount reflected is dependent on the amount of downwelling, which in turn is dependent on if/where there is a cloud above.  So the all-sky vs clear-sky radiation calculation would be impacted. This justifies the need for the separate CF names for `surface_upwelling_longwave_flux_in_air` and `surface_upwelling_longwave_flux_in_air_assuming_clear_sky`.
2. On the basis of the explanation in 1., it means that in the case of any atmospheric constituent that absorbs or scatters in the LW, this will need to be factored into the radiative flux diagnostics from any corresponding double radiation call. Therefore, there is a requirement for corresponding CF names for "no aerosol" or "reference ozone" radiation calls (i.e., `surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_no_aerosol`, and `surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air`)

It means that the CF name `surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air` implemented in this issue should be retained. However, it means that we have identified a missing CF name for the "no aerosol" case. I will open a new issue to cover this. 

Hope this helps provide some clarity.

**Comment by taylor13** [comment]
I finally see the light.  Of course, emissivity < 1 means some of the incident LW gets reflected back up and should be included in the "upwelling_longwave", which, as you point out, the upwelling longwave depends on atmospheric conditions.

I'm curious about how large the differences are between when atmospheric conditions change (e.g., from clear sky to all sky or from actual ozone to reference ozone).  Does anyone know order of magnitude?  is it ~0.1W/m^2 or ~1 W/m^2 or larger?  I don't think answering that question should delay any of the action(s) agreed above.

Thanks for reminding that <1 emissivity implies >0 reflectivity.

**Comment by fmoconnor** [comment]
Thanks @taylor13 - I think we're all still learning! The person who raised this in the context of the data request for the Radiative Forcing MIP, Carsten Abraham, indicated that there could be local differences of several W/m^2 due to cloud. From actual aerosol to zero aerosol, I think the difference will be less than that and from actual ozone to reference ozone, it is likely to be even lower. Hope that helps, Fiona

**Comment by japamment** [comment]
Dear Fiona and Karl, @fmoconnor @taylor13 

Thank you both for the interesting and informative discussion in this issue!

I see that the conclusion is that we should leave the name `surface_upwelling_longwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air` that was added at v86 of the standard name table as it is.

Issue [#236](https://github.com/cf-convention/vocabularies/issues/236) has been opened to propose one further upwelling_longwave_flux name for the "no aerosol" case discussed here.

I am therefore closing this issue again as resolved.

Best wishes,
Alison
