### ISSUE TITLE
ocean_volume vs. sea_water_volume

### ISSUE THREAD

**Issue by taylor13** [cf-convention/vocabularies#61]
What is the difference between "ocean_volume" and "sea_water_volume".  In the standard names listing, the note for sea_water_volume says "The quantity with standard name "sea_water_volume" is the total volume of liquid seawater in the global oceans, including enclosed seas."
There is no information provided regarding "ocean_volume".  Should these two names be declared aliases for the same thing?

**Comment by efisher008** [comment]
Hi @taylor13 @JonathanGregory,

I agree with the above discussion and have made the following changes in the editor (although they are currently labelled as "under discussion"): 

- `ocean_volume` aliased to `sea_water_volume`
- `ocean_volume_fraction` aliased to `sea_water_volume_fraction`: https://cfeditor.ceda.ac.uk/proposal/5380/edit

Is this what you intended? Would it also be needed to alter the description of both names to include the definition of the phrase `sea_water` i.e. add _"Sea water refers to liquid seawater in the global oceans, including enclosed seas."_? This could then be added to the CF phrasebank. The wording of this can be changed if necessary.

Another question: should I now remove the "old" `ocean_volume` name from the table? I don't believe this should cause any issues as it is now an alias of `sea_water_volume`, and the old name doesn't have a description so there is nothing to transfer. 

Best wishes,
Ellie

**Comment by JonathanGregory** [comment]
Dear Ellie

Yes, that's what was meant. It would certainly be an improvement to add the definition of `sea_water` to the description of these names, thanks. I don't think we ever _delete_ names from the table, do we. That's the reason for having aliases. There may be existing archived datasets which use the standard name `ocean_volume`, so we have to keep it in the table, as an alias of `sea_water_volume`, where its definition will go. Have I misunderstood?

Best wishes

Jonathan

**Comment by efisher008** [comment]
Dear Jonathan,

Apologies, I think I misunderstood how the name would be transformed when aliased. What I meant is that `ocean_volume` should no longer have its own entry in the table, rather it should be attached as an alias to the published name `sea_water_volume`. The way that the CF editor works currently is that a name is automatically aliased when a term change is proposed (accepted) from the previously published version. It is also possible to manually add an alias in the system without proposing a term change, which is what I had done. I thought that there would therefore be a standalone entry remaining for `ocean_volume` which would need to be dealt with, but it actually seems as though this has been taken care of when the alias was created, so there is no need to remove/'delete' anything (which as you said is not done for the standard name table). 

Best wishes,
Ellie

**Comment by efisher008** [comment]
Both changes have now been accepted as the issue previously reached a consensus and there have been no new comments to the contrary. Thank you @taylor13 @JonathanGregory for your comments.

**Comment by JonathanGregory** [comment]
Thanks for your help, Ellie, and your explanation of how the editor manages aliases.
