### ISSUE TITLE
Paleoclimate data

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/vocabularies#68]
How should paleoclimate data be represented using the CF conventions? Can existing standard names like these still be used?

- sea_surface_temperature
- sea_water_salinity

Or should new more specific standard names be introduced? Another option would be provide a long name of "years since XXXX" or "year before 2021". What would you recommend as the best practice?

Also, can parameters like the age of sediments be represented?

**Comment by roy-lowry** [comment]
@efisher008 This was a query as to whether some new Standard Names would be required, but precedents were quoted that showed none were needed. Consequently, there's no further action and I've closed the ticket.
