### ISSUE TITLE
Standard Names: Bedrock .. and heat fluxes out of bedrock

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/vocabularies#8]
There are 3 standard names which refer to bedrock, and a few more mention it in their definitions. Some of the wording appears to be ambiguous.

The intention of the term "bedrock_altitude" also needs clarification: it is supposed to give the  altitude of bedrock beneath land ice and ocean: but if it really means "bedrock", why does it not apply to the altitude of bedrock beneath soil? I suspect that it is intended to refer to the height of solid earth beneath land-ice and ocean, which may be silt or rock. It appears to be primarily used in the land-ice context, in which case the neglect of the debris between ice and rock may be OK ... but what is the purpose of referring to the altitude of bedrock below ocean?

(1) In the standard names `bedrock_altitude` and associated tendency and change terms, `bedrock`  is defined as "the solid Earth surface beneath land ice or ocean water." This definition is inappropriate for two reasons. Firstly, there will often be soil or sediment between ice or water and the bedrock and, secondly, bedrock may occur beneath the atmosphere. A more appropriate definition (from Enc. Britannica) is "solid rock that is typically buried beneath soil and other broken or unconsolidated material". There may be a need for a new term to represent the altitude of the solid earth.

(2) The term `upward_geothermal_heat_flux_at_ground_level_in_land_ice` is defined to be the upward heat flux in bedrock beneath ice, but there is likely to be a difference in the heat flux coming out of the ground and the heat flux into the ice due to horizontal transports at the interface associated with basal run-off (which is represented in some CMIP6 models).

There are comparable terms for sea ice, `downwelling_shortwave_flux_in_sea_water_at_sea_ice_base`  and soil, `upward_heat_flux_at_ground_level_in_soil`, which might be useful in giving us patterns to follow.  

`upward_geothermal_heat_flux_in_bedrock_below_land_ice` might work. I have used `below_land_ice` rather that `_at_land_ice_base` because there might be something between the land ice and the bedrock ... but is that what the people using this term want?

(3) "bedrock" also occurs in other standard name definitions. For example, 
`land_ice_vertical_mean_x_velocity` has the line "The vertical mean land ice velocity is the average from the bedrock to the surface of the ice" which clearly incorrect when the land ice is in the form of a floating ice shelf. Here, I think the it would be simpler to say "The vertical mean land ice velocity is the average from the base to the surface of the ice".

**Comment by efisher008** [comment]
Dear @martinjuckes, @JonathanGregory, @feggleton,

I am revisiting this issue as it has been open for 5 years (and 1 year since the last comments), without being fully concluded.

I can see this name is still "under discussion" in the CF editor: https://cfeditor.ceda.ac.uk/proposal/5266/edit

Is there anything now required to make this (final) name ready for acceptance? 

Best wishes,
Ellie

**Comment by JonathanGregory** [comment]
From Fran's most recent comment it appears that it's all agreed. It needed `upward_heat_flux_at_base_of_grounded_ice_sheet` to be put in the editor.

**Comment by efisher008** [comment]
Hi @JonathanGregory, @martinjuckes, @feggleton,

The remaining standard name `upward_heat_flux_at_base_of_grounded_ice_sheet`, a term change from `upward_geothermal_heat_flux_at_ground_level_in_land_ice`, has now been accepted in the editor as changes had previously been agreed. Thank you all for the discussion and hard work on this proposal. 

Best wishes,
Ellie

**Comment by efisher008** [comment]
This has been published in v86 of the Standard Names Table (released 5 September 2024).
